"""Build standalone binary for DualEntry CLI using PyInstaller."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

BUILD_INFO = ROOT / "src" / "dualentry_cli" / "_build_info.py"

PROD_BUILD_INFO = '''\
"""Build-time configuration — generated by CI."""

BUILD_MODE = "prod"
DEFAULT_API_URL = "https://api.dualentry.com"
'''


def main():
    original = BUILD_INFO.read_text()
    try:
        BUILD_INFO.write_text(PROD_BUILD_INFO)

        subprocess.run(
            [
                sys.executable,
                "-m",
                "PyInstaller",
                "--onefile",
                "--name",
                "dualentry",
                "--strip",
                "--noconfirm",
                str(ROOT / "src" / "dualentry_cli" / "main.py"),
            ],
            cwd=str(ROOT),
            check=True,
        )

        print(f"\nBinary built: {ROOT / 'dist' / 'dualentry'}")
    finally:
        BUILD_INFO.write_text(original)


if __name__ == "__main__":
    main()
